DROP TABLE Users;
DROP TABLE Book;
DROP TABLE Address;
DROP TABLE Orders ;
DROP TABLE OrderItem;
DROP TABLE VisitEvent;
DROP TABLE Review;
CREATE TABLE Book(
 	bid   INT NOT NULL,
	title Long VARGRAPHIC NOT NULL,
    author Long VARGRAPHIC NOT NULL,
 	price INT NOT NULL,
	category Long VARGRAPHIC NOT NULL,
 	PRIMARY KEY(bid)
 	);
 	

 CREATE TABLE Address(
 id   			INT    NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) ,
 street	    Long VARGRAPHIC NOT NULL,
 province   Long VARGRAPHIC  NOT NULL,
 country    Long VARGRAPHIC	 NOT NULL,
 zip	    Long VARGRAPHIC  NOT NULL,
 email	    Long VARGRAPHIC	 NOT NULL,
 PRIMARY KEY(id)
); 


CREATE TABLE Users(
 userName   VARCHAR(20)	NOT NULL,
 firstName  VARCHAR(20) NOT NULL,
 lastName   VARCHAR(20)	NOT NULL,
 passWord	VARBINARY(20) NOT NULL,   
 Email	    VARCHAR(100) NOT NULL,
 permisson  INT		NOT NULL,
 PRIMARY KEY(userName)
 );

CREATE TABLE Orders(
 id   			INT    NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) ,
 user   VARCHAR(20)   DEFAULT NOT NULL,
 address     INT  NOT NULL,
 date  DATE NOT NULL DEFAULT CURRENT_DATE,  
 PRIMARY KEY(id),
 FOREIGN KEY(address) REFERENCES Address(id) ON DELETE CASCADE,
 );
 

 CREATE TABLE OrderItem(
 id    INT   NOT NULL,
 bid   INT NOT NULL,
 QTY  INT NOT NULL,
 price INT NOT NULL,
 FOREIGN KEY(id) REFERENCES Orders(id) ON DELETE CASCADE,
 FOREIGN KEY(bid) REFERENCES Book(BID) ON DELETE CASCADE
 );

 CREATE TABLE VisitEvent(
 day   DATE NOT NULL,
 bid   INT NOT NULL,
 eventtype	   INT NOT NULL,
 FOREIGN KEY(bid) REFERENCES Book(bid)
 );

 CREATE TABLE Review(
 author Long VARGRAPHIC DEFAULT NOT NULL,
 Review	Long VARGRAPHIC DEFAULT NOT NULL
 )